name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.11", "1.12", "1.13"]
    steps:
    - uses: actions/setup-go@master
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@master
    - name: go test
      run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic ./..."
    - uses: Atrox/codecov-action@v0.1.3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
